// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/image.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImportImageReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportImageReq) Reset()         { *m = ImportImageReq{} }
func (m *ImportImageReq) String() string { return proto.CompactTextString(m) }
func (*ImportImageReq) ProtoMessage()    {}
func (*ImportImageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3b2d16d94f3a5e, []int{0}
}

func (m *ImportImageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportImageReq.Unmarshal(m, b)
}
func (m *ImportImageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportImageReq.Marshal(b, m, deterministic)
}
func (m *ImportImageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportImageReq.Merge(m, src)
}
func (m *ImportImageReq) XXX_Size() int {
	return xxx_messageInfo_ImportImageReq.Size(m)
}
func (m *ImportImageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportImageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImportImageReq proto.InternalMessageInfo

func (m *ImportImageReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ImportImageReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ImportImageReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ImportImageResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportImageResp) Reset()         { *m = ImportImageResp{} }
func (m *ImportImageResp) String() string { return proto.CompactTextString(m) }
func (*ImportImageResp) ProtoMessage()    {}
func (*ImportImageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3b2d16d94f3a5e, []int{1}
}

func (m *ImportImageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportImageResp.Unmarshal(m, b)
}
func (m *ImportImageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportImageResp.Marshal(b, m, deterministic)
}
func (m *ImportImageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportImageResp.Merge(m, src)
}
func (m *ImportImageResp) XXX_Size() int {
	return xxx_messageInfo_ImportImageResp.Size(m)
}
func (m *ImportImageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportImageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ImportImageResp proto.InternalMessageInfo

func (m *ImportImageResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ImportImageResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime           string   `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Machines             int32    `protobuf:"varint,5,opt,name=machines,proto3" json:"machines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3b2d16d94f3a5e, []int{2}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Image) GetMachines() int32 {
	if m != nil {
		return m.Machines
	}
	return 0
}

type ListImageResp struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImageResp) Reset()         { *m = ListImageResp{} }
func (m *ListImageResp) String() string { return proto.CompactTextString(m) }
func (*ListImageResp) ProtoMessage()    {}
func (*ListImageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a3b2d16d94f3a5e, []int{3}
}

func (m *ListImageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImageResp.Unmarshal(m, b)
}
func (m *ListImageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImageResp.Marshal(b, m, deterministic)
}
func (m *ListImageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImageResp.Merge(m, src)
}
func (m *ListImageResp) XXX_Size() int {
	return xxx_messageInfo_ListImageResp.Size(m)
}
func (m *ListImageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListImageResp proto.InternalMessageInfo

func (m *ListImageResp) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *ListImageResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*ImportImageReq)(nil), "pb.ImportImageReq")
	proto.RegisterType((*ImportImageResp)(nil), "pb.ImportImageResp")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*ListImageResp)(nil), "pb.ListImageResp")
}

func init() {
	proto.RegisterFile("pb/image.proto", fileDescriptor_1a3b2d16d94f3a5e)
}

var fileDescriptor_1a3b2d16d94f3a5e = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0xb1, 0x1d, 0x87, 0xe6, 0x42, 0x1d, 0xd0, 0x24, 0xd2, 0xa1, 0xae, 0xa7, 0x4c, 0x0e,
	0xb4, 0x7b, 0xb7, 0x0e, 0x81, 0x40, 0xc1, 0x74, 0x2f, 0x92, 0x23, 0x1a, 0x0d, 0x67, 0x5d, 0xcf,
	0x5a, 0x0a, 0xfd, 0xf1, 0x45, 0x52, 0x12, 0x5c, 0x5a, 0xb2, 0x3d, 0x7f, 0xe7, 0x7b, 0x7c, 0x3a,
	0xa8, 0x48, 0x6f, 0x2d, 0xaa, 0x0f, 0xd3, 0x12, 0x3b, 0xef, 0x44, 0x4e, 0x7a, 0xbd, 0x22, 0xbd,
	0xed, 0x1d, 0xa2, 0x1b, 0x12, 0x6c, 0xf6, 0x50, 0xed, 0x90, 0x1c, 0xfb, 0x5d, 0xf8, 0xb3, 0x33,
	0x9f, 0x42, 0xc0, 0x8c, 0x94, 0x3f, 0xca, 0xac, 0xce, 0x36, 0x8b, 0x2e, 0xe6, 0xc0, 0xfc, 0x17,
	0x19, 0x99, 0x27, 0x16, 0x72, 0x60, 0x83, 0x42, 0x23, 0x8b, 0xc4, 0x42, 0x6e, 0x9e, 0x61, 0xf5,
	0xab, 0x6d, 0x24, 0x51, 0x41, 0x6e, 0x0f, 0xa7, 0xb2, 0xdc, 0x1e, 0xc4, 0x1d, 0x14, 0x86, 0x39,
	0x36, 0x2d, 0x1f, 0x17, 0x2d, 0xe9, 0xf6, 0x85, 0xd9, 0x71, 0x17, 0x68, 0xf3, 0x0d, 0x65, 0xdc,
	0xfc, 0xb3, 0x75, 0x0f, 0xcb, 0x9e, 0x8d, 0xf2, 0xe6, 0xdd, 0x5b, 0x3c, 0x7b, 0x40, 0x42, 0x6f,
	0x16, 0xff, 0xb5, 0xb9, 0x58, 0xcf, 0x26, 0xd6, 0x6b, 0xb8, 0x41, 0xd5, 0x1f, 0xed, 0x60, 0x46,
	0x59, 0xd6, 0xd9, 0xa6, 0xec, 0x2e, 0xdf, 0xcd, 0x2b, 0xdc, 0xee, 0xed, 0x38, 0x71, 0x7f, 0x80,
	0x79, 0x3c, 0xe0, 0x28, 0xb3, 0xba, 0x38, 0xeb, 0xa6, 0xf1, 0x69, 0x70, 0xf5, 0x39, 0x7a, 0x1e,
	0x6f, 0xfc, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x1c, 0x01, 0xea, 0x8a, 0x01, 0x00, 0x00,
}
