// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/network.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkName struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkName) Reset()         { *m = NetworkName{} }
func (m *NetworkName) String() string { return proto.CompactTextString(m) }
func (*NetworkName) ProtoMessage()    {}
func (*NetworkName) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ca4385605dfbfc, []int{0}
}

func (m *NetworkName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkName.Unmarshal(m, b)
}
func (m *NetworkName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkName.Marshal(b, m, deterministic)
}
func (m *NetworkName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkName.Merge(m, src)
}
func (m *NetworkName) XXX_Size() int {
	return xxx_messageInfo_NetworkName.Size(m)
}
func (m *NetworkName) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkName.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkName proto.InternalMessageInfo

func (m *NetworkName) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NetworkCreateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subnet               string   `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkCreateReq) Reset()         { *m = NetworkCreateReq{} }
func (m *NetworkCreateReq) String() string { return proto.CompactTextString(m) }
func (*NetworkCreateReq) ProtoMessage()    {}
func (*NetworkCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ca4385605dfbfc, []int{1}
}

func (m *NetworkCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkCreateReq.Unmarshal(m, b)
}
func (m *NetworkCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkCreateReq.Marshal(b, m, deterministic)
}
func (m *NetworkCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkCreateReq.Merge(m, src)
}
func (m *NetworkCreateReq) XXX_Size() int {
	return xxx_messageInfo_NetworkCreateReq.Size(m)
}
func (m *NetworkCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkCreateReq proto.InternalMessageInfo

func (m *NetworkCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkCreateReq) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

func (m *NetworkCreateReq) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

type NetworkCreateResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkCreateResp) Reset()         { *m = NetworkCreateResp{} }
func (m *NetworkCreateResp) String() string { return proto.CompactTextString(m) }
func (*NetworkCreateResp) ProtoMessage()    {}
func (*NetworkCreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ca4385605dfbfc, []int{2}
}

func (m *NetworkCreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkCreateResp.Unmarshal(m, b)
}
func (m *NetworkCreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkCreateResp.Marshal(b, m, deterministic)
}
func (m *NetworkCreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkCreateResp.Merge(m, src)
}
func (m *NetworkCreateResp) XXX_Size() int {
	return xxx_messageInfo_NetworkCreateResp.Size(m)
}
func (m *NetworkCreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkCreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkCreateResp proto.InternalMessageInfo

func (m *NetworkCreateResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetworkCreateResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*NetworkName)(nil), "pb.NetworkName")
	proto.RegisterType((*NetworkCreateReq)(nil), "pb.NetworkCreateReq")
	proto.RegisterType((*NetworkCreateResp)(nil), "pb.NetworkCreateResp")
}

func init() {
	proto.RegisterFile("pb/network.proto", fileDescriptor_18ca4385605dfbfc)
}

var fileDescriptor_18ca4385605dfbfc = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0xd2, 0xcf,
	0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x92, 0xe2, 0x2f, 0x48, 0xd2, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x08, 0x2a, 0xc9, 0x72,
	0x71, 0xfb, 0x41, 0x54, 0xf9, 0x25, 0xe6, 0xa6, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x28, 0x45, 0x70, 0x09, 0x40, 0xa5, 0x9d, 0x8b,
	0x52, 0x13, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xa1,
	0xaa, 0xc0, 0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0xd2, 0xa4, 0xbc, 0xd4, 0x12, 0x09, 0x26, 0xb0,
	0x28, 0x94, 0x27, 0x24, 0xc1, 0xc5, 0x9e, 0x9e, 0x58, 0x92, 0x5a, 0x9e, 0x58, 0x29, 0xc1, 0x0c,
	0x96, 0x80, 0x71, 0x95, 0x5c, 0xb8, 0x04, 0xd1, 0x4c, 0x2e, 0x2e, 0x40, 0xb7, 0x5e, 0x48, 0x9e,
	0x8b, 0x35, 0xb5, 0xa8, 0x28, 0xbf, 0x08, 0x6c, 0x2a, 0xb7, 0x11, 0xa7, 0x5e, 0x41, 0x92, 0x9e,
	0x2b, 0x48, 0x20, 0x08, 0x22, 0x9e, 0xc4, 0x06, 0xf6, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x7f, 0x87, 0xca, 0x21, 0xee, 0x00, 0x00, 0x00,
}
