// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/volume.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Volume struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{0}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Volume) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type ListVolumeResp struct {
	Volumes              []*Volume `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Error                *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListVolumeResp) Reset()         { *m = ListVolumeResp{} }
func (m *ListVolumeResp) String() string { return proto.CompactTextString(m) }
func (*ListVolumeResp) ProtoMessage()    {}
func (*ListVolumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{1}
}

func (m *ListVolumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVolumeResp.Unmarshal(m, b)
}
func (m *ListVolumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVolumeResp.Marshal(b, m, deterministic)
}
func (m *ListVolumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVolumeResp.Merge(m, src)
}
func (m *ListVolumeResp) XXX_Size() int {
	return xxx_messageInfo_ListVolumeResp.Size(m)
}
func (m *ListVolumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVolumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListVolumeResp proto.InternalMessageInfo

func (m *ListVolumeResp) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ListVolumeResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateVolumeReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVolumeReq) Reset()         { *m = CreateVolumeReq{} }
func (m *CreateVolumeReq) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeReq) ProtoMessage()    {}
func (*CreateVolumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{2}
}

func (m *CreateVolumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeReq.Unmarshal(m, b)
}
func (m *CreateVolumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeReq.Marshal(b, m, deterministic)
}
func (m *CreateVolumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeReq.Merge(m, src)
}
func (m *CreateVolumeReq) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeReq.Size(m)
}
func (m *CreateVolumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeReq proto.InternalMessageInfo

func (m *CreateVolumeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateVolumeResp struct {
	Volume               *Volume  `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVolumeResp) Reset()         { *m = CreateVolumeResp{} }
func (m *CreateVolumeResp) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeResp) ProtoMessage()    {}
func (*CreateVolumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{3}
}

func (m *CreateVolumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeResp.Unmarshal(m, b)
}
func (m *CreateVolumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeResp.Marshal(b, m, deterministic)
}
func (m *CreateVolumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeResp.Merge(m, src)
}
func (m *CreateVolumeResp) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeResp.Size(m)
}
func (m *CreateVolumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeResp proto.InternalMessageInfo

func (m *CreateVolumeResp) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *CreateVolumeResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddVolumeReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVolumeReq) Reset()         { *m = AddVolumeReq{} }
func (m *AddVolumeReq) String() string { return proto.CompactTextString(m) }
func (*AddVolumeReq) ProtoMessage()    {}
func (*AddVolumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{4}
}

func (m *AddVolumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVolumeReq.Unmarshal(m, b)
}
func (m *AddVolumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVolumeReq.Marshal(b, m, deterministic)
}
func (m *AddVolumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVolumeReq.Merge(m, src)
}
func (m *AddVolumeReq) XXX_Size() int {
	return xxx_messageInfo_AddVolumeReq.Size(m)
}
func (m *AddVolumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVolumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddVolumeReq proto.InternalMessageInfo

func (m *AddVolumeReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AddVolumeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddVolumeResp struct {
	Volume               string   `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVolumeResp) Reset()         { *m = AddVolumeResp{} }
func (m *AddVolumeResp) String() string { return proto.CompactTextString(m) }
func (*AddVolumeResp) ProtoMessage()    {}
func (*AddVolumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{5}
}

func (m *AddVolumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVolumeResp.Unmarshal(m, b)
}
func (m *AddVolumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVolumeResp.Marshal(b, m, deterministic)
}
func (m *AddVolumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVolumeResp.Merge(m, src)
}
func (m *AddVolumeResp) XXX_Size() int {
	return xxx_messageInfo_AddVolumeResp.Size(m)
}
func (m *AddVolumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVolumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddVolumeResp proto.InternalMessageInfo

func (m *AddVolumeResp) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *AddVolumeResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteVolumeReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeReq) Reset()         { *m = DeleteVolumeReq{} }
func (m *DeleteVolumeReq) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeReq) ProtoMessage()    {}
func (*DeleteVolumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ba9d25a6793929, []int{6}
}

func (m *DeleteVolumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeReq.Unmarshal(m, b)
}
func (m *DeleteVolumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeReq.Marshal(b, m, deterministic)
}
func (m *DeleteVolumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeReq.Merge(m, src)
}
func (m *DeleteVolumeReq) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeReq.Size(m)
}
func (m *DeleteVolumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeReq proto.InternalMessageInfo

func (m *DeleteVolumeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Volume)(nil), "pb.Volume")
	proto.RegisterType((*ListVolumeResp)(nil), "pb.ListVolumeResp")
	proto.RegisterType((*CreateVolumeReq)(nil), "pb.CreateVolumeReq")
	proto.RegisterType((*CreateVolumeResp)(nil), "pb.CreateVolumeResp")
	proto.RegisterType((*AddVolumeReq)(nil), "pb.AddVolumeReq")
	proto.RegisterType((*AddVolumeResp)(nil), "pb.AddVolumeResp")
	proto.RegisterType((*DeleteVolumeReq)(nil), "pb.DeleteVolumeReq")
}

func init() {
	proto.RegisterFile("pb/volume.proto", fileDescriptor_70ba9d25a6793929)
}

var fileDescriptor_70ba9d25a6793929 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xaa, 0x91, 0x4c, 0xd4, 0xc8, 0x1e, 0x24, 0x78, 0x69, 0x59, 0x2c, 0xf4, 0x14,
	0xa1, 0x82, 0x77, 0x51, 0xc1, 0x83, 0x17, 0x83, 0xd8, 0xa3, 0x24, 0xed, 0x80, 0x81, 0x6e, 0x77,
	0xdc, 0x5d, 0xfd, 0xfd, 0xb2, 0xb3, 0x0d, 0x64, 0x41, 0xa8, 0xb7, 0xe5, 0x9b, 0x97, 0x79, 0x1f,
	0x13, 0x28, 0xa9, 0xbb, 0xf9, 0xd1, 0xdb, 0x6f, 0x85, 0x35, 0x19, 0xed, 0xb4, 0x48, 0xa9, 0xbb,
	0xf2, 0x70, 0xad, 0x95, 0xd2, 0xbb, 0x00, 0xe5, 0x2b, 0x64, 0xef, 0x1c, 0x12, 0x02, 0x8e, 0x76,
	0xad, 0xc2, 0x2a, 0x99, 0x25, 0x8b, 0xbc, 0xe1, 0xb7, 0x67, 0xd4, 0xba, 0xcf, 0x2a, 0x0d, 0xcc,
	0xbf, 0xc5, 0x14, 0x8a, 0xb5, 0xc1, 0xd6, 0xe1, 0x87, 0xeb, 0x15, 0x56, 0x13, 0x1e, 0x41, 0x40,
	0x6f, 0xbd, 0x42, 0xb9, 0x82, 0xf3, 0x97, 0xde, 0xba, 0xb0, 0xb6, 0x41, 0x4b, 0xe2, 0x1a, 0x4e,
	0x82, 0x89, 0xad, 0x92, 0xd9, 0x64, 0x51, 0x2c, 0xa1, 0xa6, 0xae, 0xde, 0x07, 0x86, 0x91, 0x98,
	0xc2, 0x31, 0x1a, 0xa3, 0x0d, 0xb7, 0x15, 0xcb, 0xdc, 0x67, 0x9e, 0x3c, 0x68, 0x02, 0x97, 0x73,
	0x28, 0x1f, 0xb8, 0x66, 0x58, 0xfd, 0xf5, 0x97, 0xb4, 0x5c, 0xc1, 0x45, 0x1c, 0xb3, 0x24, 0x24,
	0x64, 0xa1, 0x86, 0x93, 0xb1, 0xc0, 0x7e, 0x72, 0xb8, 0xff, 0x0e, 0x4e, 0xef, 0x37, 0x9b, 0xa8,
	0x9c, 0xaf, 0x93, 0x8c, 0xae, 0x33, 0x08, 0xa5, 0x23, 0xa1, 0x67, 0x38, 0x1b, 0x7d, 0x67, 0x49,
	0x5c, 0x46, 0x36, 0xf9, 0xff, 0x0d, 0xe6, 0x50, 0x3e, 0xe2, 0x16, 0x0f, 0x5c, 0xa0, 0xcb, 0xf8,
	0xdf, 0xde, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x84, 0x3b, 0xe1, 0x4b, 0x03, 0x02, 0x00, 0x00,
}
